Added the Philips Vereos to the list of scanners
NikEfth/STIR pull request #11
Opened 2019-04-22 08:06 UTC by txusser

2019-04-22 20:54 UTC, NikEfth commented
Are you sure you would like to see all the scanners int he public STIR ? You could hold on to them for now and do this after you have your papers out

2019-04-23 08:25 UTC, txusser commented
Well, the information needed to characterize the model is rather public:
https://philipsproductcontent.blob.core.windows.net/assets/20170523/360753349c5d4a6aa46ba77c015e75b4.pdf
No real point on hiding it. Anyway, no hurry on pulling it now.

2022-02-10 19:56 UTC, KrisThielemans requested changes
could you make this into a PR for just the Vereos? Then I'll squash merge

2022-02-10 19:56 UTC, KrisThielemans commented on src/recon_test/recontest.cxx
> +        return Succeeded::yes;
this is incorrect. revert

2022-02-10 19:56 UTC, KrisThielemans commented on src/recon_buildblock/IterativeReconstruction.cxx
> +  if (this->set_up(target_data_sptr) == Succeeded::no)
I see no reason for this. It doesn't belong in this PR anyway. Please revert

2022-02-10 19:56 UTC, KrisThielemans commented on src/recon_buildblock/IterativeReconstruction.cxx
> +  return this->reconstruct(target_data_sptr);
and revert this

2022-08-26 10:22 UTC, KrisThielemans commented
@txusser any chance you can finalise this?

2022-08-26 10:45 UTC, txusser commented
Hi Kris,

This project is currently on hold and rather in the hands of Pablo, but I do not expect that they may continue this in the short term unless someone new incorporates into the team. I still collaborate in the SimPET project but not into coding as I moved to a different institution in January.

2022-08-26 11:21 UTC, KrisThielemans commented
sorry to hear that, but do you want to edit this PR a tiny bit such that I can squash-merge it?

2022-09-07 09:03 UTC, txusser commented
Maybe @NikEfth is more suitable to do this

2024-01-02 09:33 UTC, KrisThielemans commented
I've added these lines to #59, although disabled, so will close this as no activity.

2024-01-02 09:33 UTC, closed without merging